### ISSUE TITLE
Bom Submission

### ISSUE THREAD

**Issue by timChase98** [QuintinCarvalho/Design_Project#1]
- [x] Missing LCSC Links
- [x] Line 6 should be 18pF 
- [x] Missing ordering information for line 11
- [x] Missing Value for line 3

Please check off the issues as you fix them. When you are done push your changes, create a new release, and close the issue with a comment that @s me. I'll review your changes and mark you as good to order parts or I'll open a new issue if you need to make changes.

**Comment by QuintinCarvalho** [comment]
Okay, ISP headers (Line 11) are a part you must order? I thought they were just pads to insert leads or wires?
________________________________

**Comment by QuintinCarvalho** [comment]
Okay, so I found out the AVR ISP header is an actual part however it is not available on the LCSC website for purchase. I did find it on another website but its neither of the main ones that we use to order parts. @timChase98

**Comment by timChase98** [comment]
That is not the correct programming header

**Comment by QuintinCarvalho** [comment]
I believe this is the correct header. @timChase98

**Comment by timChase98** [comment]
Looks Good
