### ISSUE TITLE
Schematic Submission

### ISSUE THREAD

**Issue by timChase98** [QuintinCarvalho/Design_Project#2]
- [x] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [x] Add reverse voltage protection for the battery.  Take a look at [THIS](https://www.ti.com/lit/an/slva139/slva139.pdf) App note from TI
- [x] All project files should be version controlled
- [x] That is a very poorly designed symbol for the 328PB
- [x] You can not use a 3V battery to power 5V devices
- [x] Your power nets are not consistent and should be using power flags
- [x] Why do you have two ISP headers? 
- [x] Read the datasheet for the 328PB for power and reset circuitry 

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by QuintinCarvalho** [comment]
Please check my power and reset circuitry @timChase98
